### ISSUE TITLE
RpmPackage: UnboundLocalError occurs

### ISSUE THREAD

**Issue by autumn-cpt** [devops-csmake/csmake-packaging#14]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/Csmake/CliDriver.py", line 824, in launchStep
    result = method(stepdict)
  File "/usr/lib/python2.7/dist-packages/Csmake/CsmakeModules/Packager.py", line 1243, in package
    self._doMetadataMappings()
  File "/usr/lib/python2.7/dist-packages/CsmakePackaging/CsmakeModules/RpmPackage.py", line 736, in _doMetadataMappings
    providesVersion.extend(otherVersion)
UnboundLocalError: local variable 'otherVersion' referenced before assignment
` EXCEPTION: Attempt to execute step package-fake-provides failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/Csmake/CliDriver.py", line 862, in launchStep
    raise e
UnboundLocalError: local variable 'otherVersion' referenced before assignment
```

**Comment by autumn-cpt** [comment]
<facepalm> there's a spelling error in the provides handling....
